/** UI copy is kept here for the English locale ticket; code names/paths stay verbatim. */
export const zh = {
  brand: "AtlasMode",
  tagline: "代码事实 · 图上规划",
  projectPath: "本地项目路径",
  pathHint: "输入绝对路径，例如 C:\\work\\project 或 /home/me/project",
  open: "打开并索引",
  project: "切换项目",
  chooseProject: "选择已打开的项目",
  refresh: "刷新代码",
  light: "浅色",
  dark: "深色",
  toggleTheme: "切换浅色/深色",
  loading: "正在读取本地项目…",
  working: "请求处理中…",
  error: "操作失败",
  empty: "打开本地项目，开始浏览真实代码",
  emptyHint: "选择由本机服务读取的项目目录。核心功能可离线使用。",
  entrypoints: "入口候选",
  entryHelp: "TS/JS：显式导出；Python：顶层公开命名约定。均非运行时确认入口。",
  search: "搜索函数",
  searchHint: "名称、限定名或路径",
  searchGo: "搜索",
  previous: "上一页",
  next: "下一页",
  truncated: "⚠ 结果已截断，请缩小范围或继续分页",
  noEntries: "未发现导出候选。可搜索函数并逐步展开。",
  routes: "浏览路线",
  noRoute: "不使用路线",
  routeStale: "⚠ 路线基于旧快照，请刷新路线后继续",
  routePrev: "上一步",
  routeNext: "下一步",
  focus: "聚焦步骤",
  routeHelp: "路线是讲解顺序，不表示真实调用关系。",
  graph: "代码画布",
  fact: "事实",
  plan: "规划",
  both: "事实 + 规划",
  layers: "显示层",
  relationType: "新增/改接关系类型",
  graphHelp: "点击节点查看源码；双击展开一层。拖动只保存布局。",
  graphEmpty: "选择入口、搜索结果或路线步骤以浏览子图",
  bounded: "每次展开最多 80 个节点 / 240 条关系；按需可增至 300 / 900。",
  expand: "展开一层",
  expandMore: "扩大到 300 节点",
  diagnostics: "静态分析诊断",
  sourceTab: "节点 / 源码",
  planTab: "规划编辑",
  verifyTab: "实现核对",
  inspector: "详情面板",
  noNode: "选择节点以查看文件、签名和源码。",
  source: "只读源码",
  sourceCap: "⚠ 大函数仅显示前 200 行；复制位置后可在编辑器查看完整源码。",
  copy: "复制文件与行号",
  copied: "位置已复制",
  copyFailed: "剪贴板不可用，请手动复制下面的位置。",
  noSource: "规划节点没有当前源码。文件 / 目录上下文也不代表新代码。",
  incoming: "调用者",
  outgoing: "调用目标",
  callsHelp: "静态调用证据；未解析不等于不存在。",
  contextPrev: "上一页调用",
  contextNext: "下一页调用",
  createTitle: "新规划标题",
  create: "创建规划",
  choosePlan: "选择规划",
  noPlan: "选择或创建规划",
  title: "规划标题",
  description: "说明 / 约束",
  saveTitle: "保存标题与说明",
  revision: "版本",
  baseline: "基线快照",
  validity: "服务端有效性",
  valid: "✓ 当前批准有效",
  invalid: "○ 当前无有效批准",
  approve: "确认当前 revision",
  validate: "校验规划",
  exportJson: "导出 JSON",
  exportMd: "导出 Markdown",
  verify: "核对已批准实现",
  approveHelp:
    "确认绑定当前 revision 和语义摘要。语义编辑创建新版本；拖动画布仅保存布局。",
  issues: "服务端校验结果",
  noIssues: "未报告校验问题",
  addFunction: "新增规划函数",
  name: "函数名",
  targetFile: "目标文件（仓库相对路径）",
  signature: "签名",
  functionDescription: "函数职责说明",
  add: "添加函数",
  editFunction: "编辑选中函数意图",
  saveFunction: "保存函数意图",
  movePreview: "目标文件变更预览",
  editFactHelp: "已有函数的编辑保存为移动/说明操作；当前源码事实保持原样。",
  deleteTemporary: "删除临时函数及其规划边",
  removeFact: "规划删除已有函数",
  relation: "规划关系",
  from: "起点函数",
  to: "终点函数",
  addRelation: "添加关系",
  reconnect: "保存改接关系",
  removeRelation: "删除选中关系的规划意图",
  factEdgeHelp: "改接已有调用会产生 remove_relation 和 add_relation 操作。",
  annotate: "节点说明 / 约束",
  annotationText: "说明内容",
  addAnnotation: "添加说明",
  annotationHelp: "说明仅是 annotate 操作，不产生 calls 关系。",
  operations: "变更清单",
  removeOperation: "移除操作",
  noOperations: "尚无语义变更",
  pending: "正在保存…",
  planned: "＋ 规划新增",
  anchor: "↳ 事实引用",
  code: "● 代码事实",
  folder: "目录",
  file: "文件",
  external: "外部依赖",
  function: "函数",
  sourceEvidence: "源码证据",
  noReport: "核对最近已批准的版本，显示结构证据。结果不替代行为测试。",
  reportRevision: "实际核对版本",
  satisfied: "✓ 已满足",
  unmet: "✕ 未满足",
  unknown: "? 无法判定",
  state: "状态",
  projectFacts: "项目事实",
  functions: "函数/类",
  files: "文件",
  notices: "范围与不确定性",
  viewSaved: "布局与主题自动保存",
  selectedEdge: "选中关系",
  noEdge: "可在画布点击关系后改接 / 删除，也可拖动端点。",
  noCalls: "此页没有调用证据",
  cancelEdge: "取消关系选择",
  newFileHelp:
    "新目标文件通过 add_function 的 filePath 或 move_function 明确规划；不会写入源码。",
  local: "本地 · 离线核心",
  refreshPlan: "重新读取规划",
  noServer: "请先启动本地 AtlasMode 服务。",
  graphStale: "⚠ 子图或函数上下文与当前快照不同，请刷新代码。",
  approvalHash: "批准摘要",
  included: "已索引文件",
  excluded: "排除规则",
  routeSource: "路线来源",
  note: "步骤说明",
  emptySelect: "请选择函数",
  verifyHistorical: "核对使用服务端最近一次批准的历史 revision。",
  dirty: "保存语义编辑后再确认。",
  dismiss: "关闭提示",
} as const;
